config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do 
    resources :groups do
      resources :expenses
    end
  end
  # Defines the root path route ("/")
  root "pages#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, :all, user_id: user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  def total_expenses(id)
    total = 0
    Expense.where(group_id: id).each do |expense|
      total += expense.amount
    end
    total
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :expenses

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }

  def user_name(user_id)
    User.find(user_id).name
  end

  def total_spent(id)
    expenses = Expense.where(group_id: id)
    total = 0
    expenses.each do |expense|
      total += expense.amount
    end
    total
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }

  has_many :groups, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    user_groups_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @group_id = Group.find(params[:group_id])
    @expenses = Expense.where(group_id: @group_id.id).order(created_at: :desc)
  end

  def show; end

  def new
    @group_id = Group.find(params[:group_id]).id
    @expense = Expense.new
  end

  def edit; end

  def create
    @expense = Expense.new(expense_params)
    @expense.user_id = current_user.id
    @group = Group.find(params[:group_id])

    @expense.group_id = @group.id

    if @expense.save
      redirect_to user_group_expenses_url(user_id: current_user.id, group_id: @group.id)
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'expense successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      flash[:success] = 'Group created succesfully'
      redirect_to user_groups_path(current_user)
    else
      render 'new'
    end
  end

  def show; end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end

  def new; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="w-4/5">

  <div class="flex justify-between">
  <div class="">
    <div><p><%= @group_id.name %>:</p> </div>
    <div> <p><%= expense.name %></p> </div>
   </div>    
    <div class="w-1/4">
    <p>$ <%= expense.amount %></p>
    </div>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount %>
    <%= form.number_field :amount , step: :any %>
  </div>

  <div>
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
 
</div>

app/views/expenses/index.html.erb
<div class="bg-fond_gris h-screen">
<div class="grid grid-cols-3 bg-fond_blue h-14 items-center">
 <div class="pl-4">
      <%= link_to  user_groups_path do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
    </div>
  <div class="pl-4"><h3 class="text-stone-300 font-bold text-2xl" >Expenses</h3> </div>
  <div> </div>
</div>



<div class="flex md:max-w-xl bg-white shadow-lg justify-between items-center p-2">
  <div class="w-1/10"> 
    <%= image_tag "#{@group_id.icon}.png", style: 'height:40px; width:auto;' %> 
  </div>
     
     <% if @expenses.count > 0 %>
  

 
      <div class="grid grid-cols-1 justify-items-start w-3/5 text-text_gray_1">
          <p class="font-bold text-lg"> Category: <%= @group_id.name %> </p>
          <p class="font-bold text-lg">Total spent: </p>
      </div>



<div class="">

<p class="text-text_gray font-bold text-xl">$<%= @expenses.first.total_expenses(@group_id) %></p>

</div>



  <%end %>
</div>






  <div class="p-2">

    <% @expenses.each do |expense| %>
      
<div class="flex md:max-w-xl bg-white shadow-lg mb-1">
      <div class="w-1/6"> 
          <%= image_tag "#{@group_id.icon}.png", style: 'height:40px; width:auto;' %> 
      </div>
 
      <%= render expense %>

   
  </div> 
   
   
   
   
    <% end %>

  </div>






  <div class="w-full absolute bottom-0 left-0 bg-fond_vert h-12 p-3 mb-1 flex items-center text-center">
    <%= link_to "Add a new expense", new_user_group_expense_path(user_id: current_user.id, group_id: @group_id), :class => "inline-block w-full border border-10 text-xl border-white px-6 py-2.5 bg-fond_vert text-stone-300 font-medium text-xs leading-tight uppercase shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
  </div> 




</div>

app/views/expenses/new.html.erb
<div class="bg-fond_gris h-screen">




<%= form_with(model: @expense,  url:"/users/#{current_user.id}/groups/#{@group_id}/expenses" ) do |form| %>

  <div class="flex justify-between bg-fond_blue h-14 items-center px-2">
    <div>
      <%= link_to  user_group_expenses_url(user_id: current_user.id, group_id: @group_id) do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
    </div>
    <div><h3 class="text-stone-300 font-bold">NEW expense </h3></div>
    <div class="actions text-stone-300">
      <%=  form.submit 'NEXT' %>
    </div>
  </div>


  <% if @expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% @expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br>

 <div class= "form-group-custom" >
      <%= form.text_field :name, placeholder: "Enter expense name", autofocus: true, class: "form-control
          block
          w-full
          px-3
          py-1.5
          text-base
          font-normal
          text-gray-700
          bg-white bg-clip-padding
          border border-solid border-gray-300
          rounded
          transition
          ease-in-out
          m-0
          focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
    </div>

 <div class= "form-group-custom" >
      <%= form.number_field :amount, step: :any, placeholder: "Enter expense amount", autofocus: true, class: "
        form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
      " %>
  </div>

  <div>
  

  </div> 
<% end %>




</div>

app/views/expenses/show.html.erb
<p><%= notice %></p>

<%= render @expense %>

<div>
 
</div>

app/views/groups/index.html.erb
<div class="bg-fond_gris h-screen">
<div class="bg-fond_blue grid grid-cols-3 gap-4 h-12 items-center" >
<div></div>
<div>
  <h2 class="font-bold text-stone-300 text-lg" >CATEGORIES</h2>
</div>
<div class="flex justify-end px-2.5">
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "font-bold text-stone-300 text-lg" %>
</div>


</div>

<div class="p-2">
  <% if @groups %>
    <% @groups.each do |group| %>
    <div class="md:max-w-xl bg-white shadow-lg mt-1.5">
    <a href = "/users/<%= group.user_id %>/groups/<%= group.id %>/expenses">
    <div class="grid grid-cols-5  h-1/6 items-center ">
      <div class=""> 
       <%= image_tag "#{group.icon}.png", style: 'height:40px; width:auto;' %>  
      </div>
        <div class="flex flex-col gap-1  col-span-3 text-text_gray_1">
        <p><%= group.name%></p>
        <p><%= group.user_name(group.user_id) %> </p>
        </div>

      <div class="font-bold text-text_gray " > Total: $<%= group.total_spent(group.id)%></div>
    </div>
    </a>
    </div>
    <% end %>

  <% end %>
</div>

  <div class="w-full absolute bottom-0 left-0 bg-fond_vert h-12 p-3 mb-1 flex items-center text-center">
    <%= link_to 'ADD A NEW CATEGORY', new_user_group_path(current_user), :class => "inline-block w-full border border-10 text-xl border-white px-6 py-2.5 bg-fond_vert text-stone-300 font-medium text-xs leading-tight uppercase shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
  <div>

</div>

app/views/groups/new.html.erb
  <div class="bg-fond_gris h-screen">
  
  
  
  <%= form_with(model: @group, url: user_groups_path) do |f| %>

  <div class="bg-fond_blue flex justify-between h-12 items-center px-1 mb-1">
    <div >
      <%= link_to  :back do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
    </div>
    <h2 class="font-bold text-xl text-stone-300" > NEW CATTEGORY</h2>
    <div class="actions">
      <%=  f.submit ('NEXT'), :class => "font-bold text-stone-300" %>
    </div>
  </div>

    <div class="form-group mb-6" >
      <%= f.text_field :name, placeholder: "Enter category name", autofocus: true , class: "form-control
          block
          w-full
          px-3
          py-1.5
          text-base
          font-normal
          text-gray-700
          bg-white bg-clip-padding
          border border-solid border-gray-300
          transition
          ease-in-out
          m-0
          focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"%>
    </div>

    <div class="form-group mb-6" >
      <%= f.label :icon, "Select label for an icon:", class: "text-text_gray" %>
      <%= f.select  :icon, ["Education", "Entertainment", "Healthcare", "Shopping", "Utilities", "Other" ], class: "form-select appearance-none
      block
      w-full
      px-3
      py-1.5
      text-base
      font-normal
      text-gray-700
      bg-white bg-clip-padding bg-no-repeat
      border border-solid border-gray-300
      rounded
      transition
      ease-in-out
      m-0
      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
    </div>
    

  </div> 
  
  <% end %>

  
  
  
  
  </div>



  
  

app/views/groups/show.html.erb
<div>
 <div>
      <%= link_to  :back do %>
        <%= image_tag "back.svg", style: 'height:10px; width:auto;' %>
      <% end  %>
    </div>
  <h3>Expenses</h3> 
  <div> </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'wind', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="fond_gris h-screen space-y-8">
  <div class="flex bg-fond_blue h-16 items-center justify-center">
   <h1 class="text-center leading-10 text-stone-300">BUDGET APP<h1>
  </div>
  <div class="flex items-center justify-center" >
    <%= link_to "Log in", new_user_session_path,  class: "inline-block px-8 py-4 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
   </div> 
   <div class="flex items-center justify-center">
    <%= link_to "Sign up", new_user_registration_path,  class: "inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>